[package]
name = "jsdom-native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "jsdom_native"

[dependencies]
html5ever = { path = "vendor/html5ever" }
napi = { version = "3", features = ["napi6"] }
napi-derive = "3"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
